name: crud-dd-task-mean-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # FRONTEND (Angular)
      - name: Set up Node for Angular
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies (Angular)
        working-directory: ./frontend
        run: npm install

      - name: Build Angular App
        working-directory: ./frontend
        run: npm run build --prod

      # -------------------------------
      # DOCKER LOGIN
      # -------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------------------------------
      # BUILD & PUSH DOCKER IMAGES
      # -------------------------------
      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mean-frontend:latest ./frontend

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mean-backend:latest ./backend

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mean-frontend:latest

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mean-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/crud-dd-task-mean-app
            docker compose pull
            docker compose up -d
